name: Infrastructure CI Engine

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  validate_infrastructure:
    name: Lint and Validate Terraform
    runs-on: ubuntu-latest

    steps:
      # 1. Pull down the repository code into the runner workspace
      - name: Checkout Code
        uses: actions/checkout@v4

      # 2. Setup the official HashiCorp Terraform CLI utility
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.5.7

      # 3. Enforce strict code layout style formatting rules
      - name: Check Code Formatting
        run: terraform fmt -check

      # 4. Initialize the code context to prepare for deep compilation validation
      - name: Initialize Code Compilation
        run: terraform init -backend=false

      # 5. Execute deep syntax verification compiler checks
      - name: Validate Configuration Syntax
        run: terraform validate
      # 6. RUN ENTERPRISE SECURITY SCANNING (SAST)
      # This step invokes the official Trivy engine to hunt for infrastructure flaws
      - name: Run Trivy Security Scanner
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'config' # Tell Trivy to scan IaC configuration files (Terraform)
          severity: 'CRITICAL,HIGH' # Fail the build ONLY if CRITICAL or HIGH threats are found
          exit-code: '1' # Tell the pipeline to fail (exit code 1) if vulnerabilities are detected

      # 7. AUTOMATED CD DRY-RUN: Run Terraform Plan
      # In a full live environment, this communicates with AWS. Here, it compiles the execution plan graph.
      - name: Generate Terraform Plan Blueprint
        run: terraform plan -auto-approve
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.MOCK_AWS_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.MOCK_AWS_SECRET_KEY }}
